### ISSUE TITLE
A small question about window size.

### ISSUE THREAD

**Issue by SLZWVICTOR** [karoldvl/paper-2015-esc-convnet#4]
I find this sentence in code:           window_size = 512 * (frames - 1)
    I read the paper and found that the window size in this project is 1024, so why we have to use "512*(frames-1)" instead? Looking forward to your reply, thank you.

**Comment by karolpiczak** [comment]
Ah, thanks, good catch. This can be indeed confusing, as I've had to think for a minute to remember what was my intention here.

The problem is in the not so lucky naming of variables and different windows being mentioned here and there.

To the point. The part of the code you mention:
```python

def _extract_segments(args):
    clip, filename, fold, category, category_name, augmented, frames = args

    # Due to an off-by-one bug which has not been caught earlier,
    # actually both variants (long and short) use the same
    # overlap setting (half of window size) - whereas different settings
    # were mentioned in the paper.
    #
    # The code below has been already cleaned up to reflect those changes.
    #
    # Apart from that, for reproducibility purposes it is required that
    # librosa v0.3.1 is used, as further versions drastically change
    # the delta computations.
    
    FRAMES_PER_SEGMENT = frames - 1  # 41 frames ~= 950 ms segment length @ 22050 Hz
    WINDOW_SIZE = 512 * FRAMES_PER_SEGMENT   # 23 ms per frame @ 22050 Hz
    STEP_SIZE = 512 * FRAMES_PER_SEGMENT // 2
    BANDS = 60
    
    s = 0
    segments = []

    normalization_factor = 1 / np.max(np.abs(clip)) 
    clip = clip * normalization_factor

    while len(clip[s * STEP_SIZE:s * STEP_SIZE + WINDOW_SIZE]) == WINDOW_SIZE:
        signal = clip[s * STEP_SIZE:s * STEP_SIZE + WINDOW_SIZE]

        melspec = librosa.feature.melspectrogram(signal, sr=22050, n_fft=1024, hop_length=512, n_mels=BANDS)
        logspec = librosa.logamplitude(melspec)
        logspec = logspec.T.flatten()[:, np.newaxis].T
        logspec = pd.DataFrame(data=logspec, dtype='float32', index=[0], columns=list('logspec_b{}_f{}'.format(i % BANDS, i / BANDS) for i in range(np.shape(logspec)[1])))

        if np.mean(logspec.as_matrix()) > -70.0:   # drop silent frames
            segment_meta = pd.DataFrame({'filename': filename, 'fold': fold, 'category': category, 'category_name': category_name,
                                        's_begin': s * STEP_SIZE, 's_end': s * STEP_SIZE + WINDOW_SIZE, 'augmented': augmented}, index=[0])
            segments.append(pd.concat((segment_meta, logspec), axis=1))
        s = s + 1

    segments = pd.concat(segments, ignore_index=True)
    libc.malloc_trim(0)
    return segments
```

Let's now assume we're talking only about the short variant for brevity - one training example is a segment consisting of 41 frames (segment here is a term equivalent to a spectrogram image: 60 rows/frequency bands &times; 41 columns/timepoints) .

The intention here is to take a single audio recording [`clip`] that is 5 seconds long as an argument of `_extract_segments(...)` and split it into overlapping chunks (`segments`) of such length (41 frames, i.e. approx. 950 ms), for instance:

Segment                            |    0     |        1       |        2         | ...
---------------------------   | ------ | ----------  | ----------- | ---
Approx. time span (in ms) | 0-950 | 475-1425 | 950-1900 | ...

What those variables mean then:

```python
FRAMES_PER_SEGMENT = frames - 1
```
That's the placeholder for the number of frames in one segment. By frame I mean a single column of the computed spectrogram. The `-1`, as far as I remember, was a quick dirty fix as further processing will create a segment that is one frame longer than desired.

```python
WINDOW_SIZE = 512 * FRAMES_PER_SEGMENT
```
`WINDOW_SIZE` is the **length of a single segment expressed in audio samples**. With 22050 Hz sampling rate, 512 samples is around 23 ms. So in our case one segment consists of `512 * (41 - 1) = 20480` samples, i.e. `20480 / 22050 = 0.929 (s)`.

```python
STEP_SIZE = 512 * FRAMES_PER_SEGMENT // 2
```
`STEP_SIZE` is the length of a single **step between consecutive segments** (also expressed in audio samples). We want 50% overlap, so it's `// 2`.

```python
BANDS = 60
```
That's straightforward - number of rows/mel frequency bands to compute.

Further on:
```python
while len(clip[s * STEP_SIZE:s * STEP_SIZE + WINDOW_SIZE]) == WINDOW_SIZE:
    signal = clip[s * STEP_SIZE:s * STEP_SIZE + WINDOW_SIZE]
```
we iterate over signal chunks (segments) of `WINDOW_SIZE` length, jumping by `STEP_SIZE`. So in a single step we're working on a numpy array `signal` consisting of 20480 data points (raw audio samples).

```python
melspec = librosa.feature.melspectrogram(signal, sr=22050, n_fft=1024, hop_length=512, n_mels=BANDS)
```
Now converting this signal into a spectrogram representation we use a *librosa* method with a sampling rate `sr=22050`, an FFT window of `n_fft=1024` **samples** and a hop of `hop_length=512` **samples**. Hop of 512 samples means that one column is computed for every `512 / 22050 = 0.023 (s) = 23 (ms)` with a look-ahead (`n_fft`) of `46 (ms)`.

The thing is both `n_fft` and `WINDOW_SIZE` can be described as "windows", while `hop_length` and `STEP_SIZE` describe "lengths of jumps". However, while the `n_fft` and `hop_length` refer to the spectrogram computation (and those are the numbers referred in the paper as **window size of 1024, hop length of 512**), `WINDOW_SIZE` and `STEP_SIZE` are variables used on a whole segment level. Yeah, I agree, that can be confusing.

**Caveat:**

There is indeed a small error in the paper mentioning that the short variant had 50% overlap and long variant had 90%. Due to a bug in the code (the version you see is already cleaned up) actually both variants used 50% overlap (`STEP_SIZE = 512 * FRAMES_PER_SEGMENT // 2`).

**Comment by SLZWVICTOR** [comment]
Thank you very much for your answer!
